-- PAX scheme, influenced heavily by the vs code dark plus theme,
-- shamelessly pillaged from https://github.com/Mofiqul/vscode.nvim/tree/main

-- CONFIG
local use_italic_comments = true

-- COLORS
local colors = {
    vscNone = "NONE",
    vscFront = "#D4D4D4",
    vscBack = "#1E1E1E",

    vscTabCurrent = "#1E1E1E",
    vscTabOther = "#2D2D2D",
    vscTabOutside = "#252526",

    vscLeftDark = "#252526",
    vscLeftMid = "#373737",
    vscLeftLight = "#636369",

    vscPopupFront = "#BBBBBB",
    vscPopupBack = "#272727",
    vscPopupHighlightBlue = "#004b72",
    vscPopupHighlightGray = "#343B41",

    vscSplitLight = "#898989",
    vscSplitDark = "#444444",
    vscSplitThumb = "#424242",

    vscCursorDarkDark = "#222222",
    vscCursorDark = "#51504F",
    vscCursorLight = "#AEAFAD",
    vscSelection = "#264F78",
    vscLineNumber = "#5A5A5A",

    vscDiffRedDark = "#4B1818",
    vscDiffRedLight = "#6F1313",
    vscDiffRedLightLight = "#FB0101",
    vscDiffGreenDark = "#373D29",
    vscDiffGreenLight = "#4B5632",
    vscSearchCurrent = "#515c6a",
    vscSearch = "#613315",

    vscGitAdded = "#81b88b",
    vscGitModified = "#e2c08d",
    vscGitDeleted = "#c74e39",
    vscGitRenamed = "#73c991",
    vscGitUntracked = "#73c991",
    vscGitIgnored = "#8c8c8c",
    vscGitStageModified = "#e2c08d",
    vscGitStageDeleted = "#c74e39",
    vscGitConflicting = "#e4676b",
    vscGitSubmodule = "#8db9e2",

    vscContext = "#404040",
    vscContextCurrent = "#707070",

    vscFoldBackground = "#202d39",

    -- Syntax colors
    vscGray = "#808080",
    vscViolet = "#646695",
    vscBlue = "#569CD6",
    vscAccentBlue = "#4FC1FE",
    vscDarkBlue = "#223E55",
    vscMediumBlue = "#18a2fe",
    vscLightBlue = "#9CDCFE",
    vscGreen = "#6A9955",
    vscBlueGreen = "#4EC9B0",
    vscLightGreen = "#B5CEA8",
    vscRed = "#F44747",
    vscOrange = "#CE9178",
    vscLightRed = "#D16969",
    vscYellowOrange = "#D7BA7D",
    vscYellow = "#DCDCAA",
    vscDarkYellow = "#FFD602",
    vscPink = "#C586C0",
    -- colours below were constant between light/dark themes
    vscUiBlue = "#084671",
    vscUiOrange = "#f28b25",
    vscPopupHighlightLightBlue = "#d7eafe",
}

local theme = {}

-- I think that this clears anything that exists, which is perhaps redundant
-- given that I think the way hl() is called blasts existing config away.
-- Probably sensible to keep this though as I'd hope it would make it clear
-- when we have items that need a bit of attention in new plugins.
vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then
    vim.cmd("syntax reset")
end

vim.g.colors_name = "pax"

-- HELPER
local function set_highlights(highlights)
    for name, val in pairs(highlights) do
        vim.api.nvim_set_hl(0, name, val)
    end
end

-- HIGHLIGHT GROUPS
-- nb a _lot_ of stuff was deleted from here. original ref is at
-- https://github.com/Mofiqul/vscode.nvim/blob/main/lua/vscode/theme.lua
local c = colors

-- We split by area here - expect these will be pulled out into separate files
-- when the overall structure is decided.
local builtins = {
    -- General
    Normal = { fg = c.vscFront, bg = c.vscBack },
    ColorColumn = { fg = "NONE", bg = c.vscCursorDarkDark },
    Cursor = { fg = c.vscCursorDark, bg = c.vscCursorLight },
    CursorLine = { bg = c.vscCursorDarkDark },
    CursorColumn = { fg = "NONE", bg = c.vscCursorDarkDark },
    Directory = { fg = c.vscBlue, bg = c.vscBack },
    DiffAdd = { fg = "NONE", bg = c.vscDiffGreenLight },
    DiffChange = { fg = "NONE", bg = c.vscDiffRedDark },
    DiffDelete = { fg = "NONE", bg = c.vscDiffRedLight },
    DiffText = { fg = "NONE", bg = c.vscDiffRedLight },
    EndOfBuffer = { fg = c.vscBack, bg = "NONE" },
    ErrorMsg = { fg = c.vscRed, bg = c.vscBack },
    VertSplit = { fg = c.vscSplitDark, bg = c.vscBack },
    Folded = { fg = "NONE", bg = c.vscFoldBackground },
    FoldColumn = { fg = c.vscLineNumber, bg = c.vscBack },
    SignColumn = { fg = "NONE", bg = c.vscBack },
    IncSearch = { fg = c.vscNone, bg = c.vscSearchCurrent },
    LineNr = { fg = c.vscLineNumber, bg = c.vscBack },
    CursorLineNr = { fg = c.vscPopupFront, bg = c.vscBack },
    MatchParen = { fg = c.vscNone, bg = c.vscCursorDark },
    ModeMsg = { fg = c.vscFront, bg = c.vscLeftDark },
    MoreMsg = { fg = c.vscFront, bg = c.vscLeftDark },
    NonText = { fg = c.vscLineNumber, bg = c.vscNone },
    Pmenu = { fg = c.vscPopupFront, bg = c.vscPopupBack },
    PmenuSel = { fg = c.vscPopupFront, bg = c.vscPopupHighlightBlue },
    PmenuSbar = { fg = "NONE", bg = c.vscPopupHighlightGray },
    PmenuThumb = { fg = "NONE", bg = c.vscPopupFront },
    Question = { fg = c.vscBlue, bg = c.vscBack },
    Search = { fg = c.vscNone, bg = c.vscSearch },
    SpecialKey = { fg = c.vscBlue, bg = c.vscNone },
    StatusLine = { fg = c.vscFront, bg = c.vscLeftMid },
    StatusLineNC = { fg = c.vscFront, bg = c.vscLeftDark },
    TabLine = { fg = c.vscFront, bg = c.vscTabOther },
    TabLineFill = { fg = c.vscFront, bg = c.vscTabOutside },
    TabLineSel = { fg = c.vscFront, bg = c.vscTabCurrent },
    Title = { fg = c.vscNone, bg = c.vscNone, bold = true },
    Visual = { fg = c.vscNone, bg = c.vscSelection },
    VisualNOS = { fg = c.vscNone, bg = c.vscSelection },
    WarningMsg = { fg = c.vscRed, bg = c.vscBack, bold = true },
    WildMenu = { fg = c.vscNone, bg = c.vscSelection },
    Comment = { fg = c.vscGreen, bg = "NONE", italic = use_italic_comments },
    Constant = { fg = c.vscBlue, bg = "NONE" },
    String = { fg = c.vscOrange, bg = "NONE" },
    Character = { fg = c.vscOrange, bg = "NONE" },
    Number = { fg = c.vscLightGreen, bg = "NONE" },
    Boolean = { fg = c.vscBlue, bg = "NONE" },
    Float = { fg = c.vscLightGreen, bg = "NONE" },
    Identifier = { fg = c.vscLightBlue, bg = "NONE" },
    Function = { fg = c.vscYellow, bg = "NONE" },
    Statement = { fg = c.vscPink, bg = "NONE" },
    Conditional = { fg = c.vscPink, bg = "NONE" },
    Repeat = { fg = c.vscPink, bg = "NONE" },
    Label = { fg = c.vscPink, bg = "NONE" },
    Operator = { fg = c.vscFront, bg = "NONE" },
    Keyword = { fg = c.vscPink, bg = "NONE" },
    Exception = { fg = c.vscPink, bg = "NONE" },
    PreProc = { fg = c.vscPink, bg = "NONE" },
    Include = { fg = c.vscPink, bg = "NONE" },
    Define = { fg = c.vscPink, bg = "NONE" },
    Macro = { fg = c.vscPink, bg = "NONE" },
    Type = { fg = c.vscBlue, bg = "NONE" },
    StorageClass = { fg = c.vscBlue, bg = "NONE" },
    Structure = { fg = c.vscBlueGreen, bg = "NONE" },
    Typedef = { fg = c.vscBlue, bg = "NONE" },
    Special = { fg = c.vscYellowOrange, bg = "NONE" },
    SpecialChar = { fg = c.vscFront, bg = "NONE" },
    Tag = { fg = c.vscFront, bg = "NONE" },
    Delimiter = { fg = c.vscFront, bg = "NONE" },
    SpecialComment = { fg = c.vscGreen, bg = "NONE" },
    Debug = { fg = c.vscFront, bg = "NONE" },
    Underlined = { fg = c.vscNone, bg = "NONE", underline = true },
    Conceal = { fg = c.vscFront, bg = c.vscBack },
    Ignore = { fg = c.vscFront, bg = "NONE" },
    Error = { fg = c.vscRed, bg = c.vscBack, undercurl = true, sp = c.vscRed },
    Todo = { fg = c.vscYellowOrange, bg = c.vscBack, bold = true },
    SpellBad = { fg = c.vscRed, bg = c.vscBack, undercurl = true, sp = c.vscRed },
    SpellCap = { fg = c.vscRed, bg = c.vscBack, undercurl = true, sp = c.vscRed },
    SpellRare = { fg = c.vscRed, bg = c.vscBack, undercurl = true, sp = c.vscRed },
    SpellLocal = { fg = c.vscRed, bg = c.vscBack, undercurl = true, sp = c.vscRed },
    Whitespace = { fg = c.vscLineNumber },

    -- LSP
    DiagnosticError = { fg = c.vscRed, bg = "NONE" },
    DiagnosticWarn = { fg = c.vscYellow, bg = "NONE" },
    DiagnosticInfo = { fg = c.vscBlue, bg = "NONE" },
    DiagnosticHint = { fg = c.vscBlue, bg = "NONE" },
    DiagnosticUnderlineError = { fg = "NONE", bg = "NONE", undercurl = true, sp = c.vscRed },
    DiagnosticUnderlineWarn = { fg = "NONE", bg = "NONE", undercurl = true, sp = c.vscYellow },
    DiagnosticUnderlineInfo = { fg = "NONE", bg = "NONE", undercurl = true, sp = c.vscBlue },
    DiagnosticUnderlineHint = { fg = "NONE", bg = "NONE", undercurl = true, sp = c.vscBlue },
    LspReferenceText = { fg = "NONE", bg = c.vscPopupHighlightGray },
    LspReferenceRead = { fg = "NONE", bg = c.vscPopupHighlightGray },
    LspReferenceWrite = { fg = "NONE", bg = c.vscPopupHighlightGray },
    -- find out if this is an internal, I think it probably is, or perhaps
    -- it is used by nvim lsp config? who knows
    LspFloatWinNormal = { fg = c.vscFront, bg = "NONE" },
    LspFloatWinBorder = { fg = c.vscLineNumber, bg = "NONE" },

    -- Legacy groups for official git.vim and diff.vim syntax
    diffAdded = { link = "DiffAdd" },
    diffChanged = { link = "DiffChange" },
    diffRemoved = { link = "DiffDelete" },
}
set_highlights(builtins)

local plugins = {
    -- Treesitter
    ["@error"] = { fg = c.vscRed, bg = "NONE" },
    ["@punctuation.bracket"] = { fg = c.vscFront, bg = "NONE" },
    ["@punctuation.special"] = { fg = c.vscFront, bg = "NONE" },
    ["@comment"] = { fg = c.vscGreen, bg = "NONE", italic = use_italic_comments },
    ["@constant"] = { fg = c.vscAccentBlue, bg = "NONE" },
    ["@constant.builtin"] = { fg = c.vscBlue, bg = "NONE" },
    ["@constant.macro"] = { fg = c.vscBlueGreen, bg = "NONE" },
    ["@string.regex"] = { fg = c.vscOrange, bg = "NONE" },
    ["@string"] = { fg = c.vscOrange, bg = "NONE" },
    ["@character"] = { fg = c.vscOrange, bg = "NONE" },
    ["@number"] = { fg = c.vscLightGreen, bg = "NONE" },
    ["@boolean"] = { fg = c.vscBlue, bg = "NONE" },
    ["@float"] = { fg = c.vscLightGreen, bg = "NONE" },
    ["@annotation"] = { fg = c.vscYellow, bg = "NONE" },
    ["@attribute"] = { fg = c.vscYellow, bg = "NONE" },
    ["@attribute.builtin"] = { fg = c.vscBlueGreen, bg = "NONE" },
    ["@namespace"] = { fg = c.vscBlueGreen, bg = "NONE" },
    ["@function.builtin"] = { fg = c.vscYellow, bg = "NONE" },
    ["@function"] = { fg = c.vscYellow, bg = "NONE" },
    ["@function.macro"] = { fg = c.vscYellow, bg = "NONE" },
    ["@parameter"] = { fg = c.vscLightBlue, bg = "NONE" },
    ["@parameter.reference"] = { fg = c.vscLightBlue, bg = "NONE" },
    ["@method"] = { fg = c.vscYellow, bg = "NONE" },
    ["@field"] = { fg = c.vscLightBlue, bg = "NONE" },
    ["@property"] = { fg = c.vscLightBlue, bg = "NONE" },
    ["@constructor"] = { fg = c.vscBlueGreen, bg = "NONE" },
    ["@conditional"] = { fg = c.vscPink, bg = "NONE" },
    ["@repeat"] = { fg = c.vscPink, bg = "NONE" },
    ["@label"] = { fg = c.vscLightBlue, bg = "NONE" },
    ["@keyword"] = { fg = c.vscPink, bg = "NONE" },
    ["@keyword.function"] = { fg = c.vscBlue, bg = "NONE" },
    ["@keyword.operator"] = { fg = c.vscBlue, bg = "NONE" },
    ["@operator"] = { fg = c.vscFront, bg = "NONE" },
    ["@exception"] = { fg = c.vscPink, bg = "NONE" },
    ["@type"] = { fg = c.vscBlueGreen, bg = "NONE" },
    ["@type.builtin"] = { fg = c.vscBlue, bg = "NONE" },
    ["@type.qualifier"] = { fg = c.vscBlue, bg = "NONE" },
    ["@storageClass"] = { fg = c.vscBlue, bg = "NONE" },
    ["@structure"] = { fg = c.vscLightBlue, bg = "NONE" },
    ["@include"] = { fg = c.vscPink, bg = "NONE" },
    ["@variable"] = { fg = c.vscLightBlue, bg = "NONE" },
    ["@variable.builtin"] = { fg = c.vscLightBlue, bg = "NONE" },
    ["@text"] = { fg = c.vscFront, bg = "NONE" },
    ["@text.underline"] = { fg = c.vscYellowOrange, bg = "NONE" },
    ["@tag"] = { fg = c.vscBlue, bg = "NONE" },
    ["@tag.delimiter"] = { fg = c.vscGray, bg = "NONE" },
    ["@tag.attribute"] = { fg = c.vscLightBlue, bg = "NONE" },
    ["@text.title"] = { fg = c.vscBlue, bold = true },
    ["@text.literal"] = { fg = c.vscFront, bg = "NONE" },
    ["@text.literal.markdown"] = { fg = c.vscOrange, bg = "NONE" },
    ["@text.literal.markdown_inline"] = { fg = c.vscOrange, bg = "NONE" },
    ["@text.emphasis"] = { fg = c.vscFront, bg = "NONE", italic = true },
    ["@text.strong"] = { fg = c.vscBlue, bold = true },
    ["@text.uri"] = { fg = c.vscFront, bg = "NONE" },
    ["@textReference"] = { fg = c.vscOrange },
    ["@punctuation.delimiter"] = { fg = c.vscFront, bg = "NONE" },
    ["@stringEscape"] = { fg = c.vscOrange, bold = true },
    ["@text.note"] = { fg = c.vscBlueGreen, bg = "NONE", bold = true },
    ["@text.warning"] = { fg = c.vscYellowOrange, bg = "NONE", bold = true },
    ["@text.danger"] = { fg = c.vscRed, bg = "NONE", bold = true },
    ["@text.diff.add"] = { link = "DiffAdd" },
    ["@text.diff.delete"] = { link = "DiffDelete" },

    -- LSP semantic tokens
    ["@lsp.typemod.type.defaultLibrary"] = { link = "@type.builtin" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type" },
    ["@lsp.type.macro"] = { link = "@constant" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@event"] = { link = "Identifier" },
    ["@interface"] = { link = "Identifier" },
    ["@modifier"] = { link = "Identifier" },
    ["@regexp"] = { fg = c.vscRed, bg = "NONE" },
    ["@decorator"] = { link = "Identifier" },

    -- Telescope
    TelescopePromptBorder = { fg = c.vscLineNumber, bg = "NONE" },
    TelescopeResultsBorder = { fg = c.vscLineNumber, bg = "NONE" },
    TelescopePreviewBorder = { fg = c.vscLineNumber, bg = "NONE" },
    TelescopeNormal = { fg = c.vscFront, bg = "NONE" },
    TelescopeSelection = { fg = c.vscFront, bg = c.vscPopupHighlightBlue },
    TelescopeMultiSelection = { fg = c.vscFront, bg = c.vscPopupHighlightBlue },
    TelescopeMatching = { fg = c.vscMediumBlue, bg = "NONE", bold = true },
    TelescopePromptPrefix = { fg = c.vscFront, bg = "NONE" },

    -- ...Lualine?
    -- symbols-outline
    -- white fg and lualine blue bg
    FocusedSymbol = { fg = "#ffffff", bg = c.vscUiBlue },
    SymbolsOutlineConnector = { fg = c.vscLineNumber, bg = "NONE" },
}
set_highlights(plugins)

local languages = {
    -- Markdown
    markdownBold = { fg = c.vscBlue, bold = true },
    markdownCode = { fg = c.vscOrange, bg = "NONE" },
    markdownRule = { fg = c.vscBlue, bold = true },
    markdownCodeDelimiter = { fg = c.vscFront, bg = "NONE" },
    markdownHeadingDelimiter = { fg = c.vscBlue, bg = "NONE" },
    markdownFootnote = { fg = c.vscOrange, bg = "NONE" },
    markdownFootnoteDefinition = { fg = c.vscOrange },
    markdownUrl = { fg = c.vscFront, bg = "NONE", underline = true },
    markdownLinkText = { fg = c.vscOrange },
    markdownEscape = { fg = c.vscOrange },

    -- Asciidoc
    asciidocAttributeEntry = { fg = c.vscYellowOrange },
    asciidocAttributeList = { fg = c.vscPink },
    asciidocAttributeRef = { fg = c.vscYellowOrange },
    asciidocHLabel = { fg = c.vscBlue, bold = true },
    asciidocListingBlock = { fg = c.vscOrange },
    asciidocMacroAttributes = { fg = c.vscYellowOrange },
    asciidocOneLineTitle = { fg = c.vscBlue, bold = true },
    asciidocPassthroughBlock = { fg = c.vscBlue },
    asciidocQuotedMonospaced = { fg = c.vscOrange },
    asciidocTriplePlusPassthrough = { fg = c.vscYellow },
    asciidocMacro = { fg = c.vscPink },
    asciidocAdmonition = { fg = c.vscOrange },
    asciidocQuotedEmphasized = { fg = c.vscBlue, italic = true },
    asciidocQuotedEmphasized2 = { fg = c.vscBlue, italic = true },
    asciidocQuotedEmphasizedItalic = { fg = c.vscBlue, italic = true },
    asciidocBackslash = { link = "Keyword" },
    asciidocQuotedBold = { link = "markdownBold" },
    asciidocQuotedMonospaced2 = { link = "asciidocQuotedMonospaced" },
    asciidocQuotedUnconstrainedBold = { link = "asciidocQuotedBold" },
    asciidocQuotedUnconstrainedEmphasized = { link = "asciidocQuotedEmphasized" },
    asciidocURL = { link = "markdownUrl" },

    -- JSON
    jsonKeyword = { fg = c.vscLightBlue, bg = "NONE" },
    jsonEscape = { fg = c.vscYellowOrange, bg = "NONE" },
    jsonNull = { fg = c.vscBlue, bg = "NONE" },
    jsonBoolean = { fg = c.vscBlue, bg = "NONE" },

    -- HTML
    htmlTag = { fg = c.vscGray, bg = "NONE" },
    htmlEndTag = { fg = c.vscGray, bg = "NONE" },
    htmlTagName = { fg = c.vscBlue, bg = "NONE" },
    htmlSpecialTagName = { fg = c.vscBlue, bg = "NONE" },
    htmlArg = { fg = c.vscLightBlue, bg = "NONE" },

    -- CSS
    cssBraces = { fg = c.vscFront, bg = "NONE" },
    cssInclude = { fg = c.vscPink, bg = "NONE" },
    cssTagName = { fg = c.vscYellowOrange, bg = "NONE" },
    cssClassName = { fg = c.vscYellowOrange, bg = "NONE" },
    cssPseudoClass = { fg = c.vscYellowOrange, bg = "NONE" },
    cssPseudoClassId = { fg = c.vscYellowOrange, bg = "NONE" },
    cssPseudoClassLang = { fg = c.vscYellowOrange, bg = "NONE" },
    cssIdentifier = { fg = c.vscYellowOrange, bg = "NONE" },
    cssProp = { fg = c.vscLightBlue, bg = "NONE" },
    cssDefinition = { fg = c.vscLightBlue, bg = "NONE" },
    cssAttr = { fg = c.vscOrange, bg = "NONE" },
    cssAttrRegion = { fg = c.vscOrange, bg = "NONE" },
    cssColor = { fg = c.vscOrange, bg = "NONE" },
    cssFunction = { fg = c.vscOrange, bg = "NONE" },
    cssFunctionName = { fg = c.vscOrange, bg = "NONE" },
    cssVendor = { fg = c.vscOrange, bg = "NONE" },
    cssValueNumber = { fg = c.vscOrange, bg = "NONE" },
    cssValueLength = { fg = c.vscOrange, bg = "NONE" },
    cssUnitDecorators = { fg = c.vscOrange, bg = "NONE" },
    cssStyle = { fg = c.vscLightBlue, bg = "NONE" },
    cssImportant = { fg = c.vscBlue, bg = "NONE" },

    -- JavaScript
    jsVariableDef = { fg = c.vscLightBlue, bg = "NONE" },
    jsFuncArgs = { fg = c.vscLightBlue, bg = "NONE" },
    jsFuncBlock = { fg = c.vscLightBlue, bg = "NONE" },
    jsRegexpString = { fg = c.vscLightRed, bg = "NONE" },
    jsThis = { fg = c.vscBlue, bg = "NONE" },
    jsOperatorKeyword = { fg = c.vscBlue, bg = "NONE" },
    jsDestructuringBlock = { fg = c.vscLightBlue, bg = "NONE" },
    jsObjectKey = { fg = c.vscLightBlue, bg = "NONE" },
    jsGlobalObjects = { fg = c.vscBlueGreen, bg = "NONE" },
    jsModuleKeyword = { fg = c.vscLightBlue, bg = "NONE" },
    jsClassDefinition = { fg = c.vscBlueGreen, bg = "NONE" },
    jsClassKeyword = { fg = c.vscBlue, bg = "NONE" },
    jsExtendsKeyword = { fg = c.vscBlue, bg = "NONE" },
    jsExportDefault = { fg = c.vscPink, bg = "NONE" },
    jsFuncCall = { fg = c.vscYellow, bg = "NONE" },
    jsObjectValue = { fg = c.vscLightBlue, bg = "NONE" },
    jsParen = { fg = c.vscLightBlue, bg = "NONE" },
    jsObjectProp = { fg = c.vscLightBlue, bg = "NONE" },
    jsIfElseBlock = { fg = c.vscLightBlue, bg = "NONE" },
    jsParenIfElse = { fg = c.vscLightBlue, bg = "NONE" },
    jsSpreadOperator = { fg = c.vscLightBlue, bg = "NONE" },
    jsSpreadExpression = { fg = c.vscLightBlue, bg = "NONE" },

    -- Typescript
    typescriptLabel = { fg = c.vscLightBlue, bg = "NONE" },
    typescriptExceptions = { fg = c.vscLightBlue, bg = "NONE" },
    typescriptBraces = { fg = c.vscFront, bg = "NONE" },
    typescriptEndColons = { fg = c.vscLightBlue, bg = "NONE" },
    typescriptParens = { fg = c.vscFront, bg = "NONE" },
    typescriptDocTags = { fg = c.vscBlue, bg = "NONE" },
    typescriptDocComment = { fg = c.vscBlueGreen, bg = "NONE" },
    typescriptLogicSymbols = { fg = c.vscLightBlue, bg = "NONE" },
    typescriptImport = { fg = c.vscPink, bg = "NONE" },
    typescriptBOM = { fg = c.vscLightBlue, bg = "NONE" },
    typescriptVariableDeclaration = { fg = c.vscLightBlue, bg = "NONE" },
    typescriptVariable = { fg = c.vscBlue, bg = "NONE" },
    typescriptExport = { fg = c.vscPink, bg = "NONE" },
    typescriptAliasDeclaration = { fg = c.vscBlueGreen, bg = "NONE" },
    typescriptAliasKeyword = { fg = c.vscBlue, bg = "NONE" },
    typescriptClassName = { fg = c.vscBlueGreen, bg = "NONE" },
    typescriptAccessibilityModifier = { fg = c.vscBlue, bg = "NONE" },
    typescriptOperator = { fg = c.vscBlue, bg = "NONE" },
    typescriptArrowFunc = { fg = c.vscBlue, bg = "NONE" },
    typescriptMethodAccessor = { fg = c.vscBlue, bg = "NONE" },
    typescriptMember = { fg = c.vscYellow, bg = "NONE" },
    typescriptTypeReference = { fg = c.vscBlueGreen, bg = "NONE" },
    typescriptTemplateSB = { fg = c.vscYellowOrange, bg = "NONE" },
    typescriptArrowFuncArg = { fg = c.vscLightBlue, bg = "NONE" },
    typescriptParamImpl = { fg = c.vscLightBlue, bg = "NONE" },
    typescriptFuncComma = { fg = c.vscLightBlue, bg = "NONE" },
    typescriptCastKeyword = { fg = c.vscLightBlue, bg = "NONE" },
    typescriptCall = { fg = c.vscBlue, bg = "NONE" },
    typescriptCase = { fg = c.vscLightBlue, bg = "NONE" },
    typescriptReserved = { fg = c.vscPink, bg = "NONE" },
    typescriptDefault = { fg = c.vscLightBlue, bg = "NONE" },
    typescriptDecorator = { fg = c.vscYellow, bg = "NONE" },
    typescriptPredefinedType = { fg = c.vscBlueGreen, bg = "NONE" },
    typescriptClassHeritage = { fg = c.vscBlueGreen, bg = "NONE" },
    typescriptClassExtends = { fg = c.vscBlue, bg = "NONE" },
    typescriptClassKeyword = { fg = c.vscBlue, bg = "NONE" },
    typescriptBlock = { fg = c.vscLightBlue, bg = "NONE" },
    typescriptDOMDocProp = { fg = c.vscLightBlue, bg = "NONE" },
    typescriptTemplateSubstitution = { fg = c.vscLightBlue, bg = "NONE" },
    typescriptClassBlock = { fg = c.vscLightBlue, bg = "NONE" },
    typescriptFuncCallArg = { fg = c.vscLightBlue, bg = "NONE" },
    typescriptIndexExpr = { fg = c.vscLightBlue, bg = "NONE" },
    typescriptConditionalParen = { fg = c.vscLightBlue, bg = "NONE" },
    typescriptArray = { fg = c.vscYellow, bg = "NONE" },
    typescriptES6SetProp = { fg = c.vscLightBlue, bg = "NONE" },
    typescriptObjectLiteral = { fg = c.vscLightBlue, bg = "NONE" },
    typescriptTypeParameter = { fg = c.vscBlueGreen, bg = "NONE" },
    typescriptEnumKeyword = { fg = c.vscBlue, bg = "NONE" },
    typescriptEnum = { fg = c.vscBlueGreen, bg = "NONE" },
    typescriptLoopParen = { fg = c.vscLightBlue, bg = "NONE" },
    typescriptParenExp = { fg = c.vscLightBlue, bg = "NONE" },
    typescriptModule = { fg = c.vscLightBlue, bg = "NONE" },
    typescriptAmbientDeclaration = { fg = c.vscBlue, bg = "NONE" },
    typescriptFuncTypeArrow = { fg = c.vscBlue, bg = "NONE" },
    typescriptInterfaceHeritage = { fg = c.vscBlueGreen, bg = "NONE" },
    typescriptInterfaceName = { fg = c.vscBlueGreen, bg = "NONE" },
    typescriptInterfaceKeyword = { fg = c.vscBlue, bg = "NONE" },
    typescriptInterfaceExtends = { fg = c.vscBlue, bg = "NONE" },
    typescriptGlobal = { fg = c.vscBlueGreen, bg = "NONE" },
    typescriptAsyncFuncKeyword = { fg = c.vscBlue, bg = "NONE" },
    typescriptFuncKeyword = { fg = c.vscBlue, bg = "NONE" },
    typescriptGlobalMethod = { fg = c.vscYellow, bg = "NONE" },
    typescriptPromiseMethod = { fg = c.vscYellow, bg = "NONE" },

    -- XML
    xmlTag = { fg = c.vscBlue, bg = "NONE" },
    xmlTagName = { fg = c.vscBlue, bg = "NONE" },
    xmlEndTag = { fg = c.vscBlue, bg = "NONE" },

    -- Python
    pythonStatement = { fg = c.vscBlue, bg = "NONE" },
    pythonOperator = { fg = c.vscBlue, bg = "NONE" },
    pythonException = { fg = c.vscPink, bg = "NONE" },
    pythonExClass = { fg = c.vscBlueGreen, bg = "NONE" },
    pythonBuiltinObj = { fg = c.vscLightBlue, bg = "NONE" },
    pythonBuiltinType = { fg = c.vscBlueGreen, bg = "NONE" },
    pythonBoolean = { fg = c.vscBlue, bg = "NONE" },
    pythonNone = { fg = c.vscBlue, bg = "NONE" },
    pythonTodo = { fg = c.vscBlue, bg = "NONE" },
    pythonClassVar = { fg = c.vscBlue, bg = "NONE" },
    pythonClassDef = { fg = c.vscBlueGreen, bg = "NONE" },

    -- TeX
    texStatement = { fg = c.vscBlue, bg = "NONE" },
    texBeginEnd = { fg = c.vscYellow, bg = "NONE" },
    texBeginEndName = { fg = c.vscLightBlue, bg = "NONE" },
    texOption = { fg = c.vscLightBlue, bg = "NONE" },
    texBeginEndModifier = { fg = c.vscLightBlue, bg = "NONE" },
    texDocType = { fg = c.vscPink, bg = "NONE" },
    texDocTypeArgs = { fg = c.vscLightBlue, bg = "NONE" },

    -- Git
    gitcommitHeader = { fg = c.vscGray, bg = "NONE" },
    gitcommitOnBranch = { fg = c.vscGray, bg = "NONE" },
    gitcommitBranch = { fg = c.vscPink, bg = "NONE" },
    gitcommitComment = { fg = c.vscGray, bg = "NONE" },
    gitcommitSelectedType = { fg = c.vscGreen, bg = "NONE" },
    gitcommitSelectedFile = { fg = c.vscGreen, bg = "NONE" },
    gitcommitDiscardedType = { fg = c.vscRed, bg = "NONE" },
    gitcommitDiscardedFile = { fg = c.vscRed, bg = "NONE" },
    gitcommitOverflow = { fg = c.vscRed, bg = "NONE" },
    gitcommitSummary = { fg = c.vscPink, bg = "NONE" },
    gitcommitBlank = { fg = c.vscPink, bg = "NONE" },

    -- Lua
    luaFuncCall = { fg = c.vscYellow, bg = "NONE" },
    luaFuncArgName = { fg = c.vscLightBlue, bg = "NONE" },
    luaFuncKeyword = { fg = c.vscPink, bg = "NONE" },
    luaLocal = { fg = c.vscPink, bg = "NONE" },
    luaBuiltIn = { fg = c.vscBlue, bg = "NONE" },

    -- SH
    shDeref = { fg = c.vscLightBlue, bg = "NONE" },
    shVariable = { fg = c.vscLightBlue, bg = "NONE" },

    -- SQL
    sqlKeyword = { fg = c.vscPink, bg = "NONE" },
    sqlFunction = { fg = c.vscYellowOrange, bg = "NONE" },
    sqlOperator = { fg = c.vscPink, bg = "NONE" },

    -- YAML
    yamlKey = { fg = c.vscBlue, bg = "NONE" },
    yamlConstant = { fg = c.vscBlue, bg = "NONE" },
}
set_highlights(languages)
